sudo: required
  
language: python

python:
    - 2.7
    - 3.6
    - 3.8
    ## PyPy versions
    #- pypy2.7-6.0
    #- pypy3

jobs:
  allow_failures:
    - python: 2.7

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev
            - libhdf5-dev
            - tcsh
            - swig
            - libcfitsio-dev

install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        h5py
    - pip install git+https://github.com/lwa-project/lsl.git
    - pip install pylint
    - make

before_script:
    - git clone https://github.com/lwa-project/psrfits_utils.git
    - cd psrfits_utils
    - ./prepare
    - ./configure --prefix=${HOME}/local/
    - make
    - make install
    - cd ..

script:
    - export LPE=`pwd`
    - export PFU=`ls -d ${HOME}/local/lib/python*/site-packages/psrfits_utils | head -n1`
    - export LD_LIBRARY_PATH=${HOME}/local/lib:${PFU}:${LPE}:${LD_LIBRARY_PATH}
    - export PYTHONPATH=${LPE}:${PFU}:${PYTHONPATH}
    - cd tests
    - python -m unittest discover
