name: Test
on:
  push:
  pull_request:
  schedule:
    - cron:  '30 5 3 * *'
jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: 'same_content'
          paths_ignore: '["README.md"]'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  build:
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.10', '3.12']
        include:
          - os: ubuntu-20.04
            python-version: '3.6'
          - os: macos-latest
            python-version: '3.6'
      fail-fast: false
    steps:
        - name: "Software Install - Ubuntu"
          if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04' }}
          run: |
            sudo apt-get install -y \
              build-essential \
              ca-certificates \
              curl \
              git \
              gzip \
              libcfitsio-dev \
              libfftw3-dev \
              libgdbm-dev \
              libgtk-3-dev \
              libhdf5-dev \
              pkg-config \
              tcsh \
              swig
        - name: "Software Install - MacOS"
          if: ${{ matrix.os == 'macos-latest' }}
          run: |
            brew install \
              autoconf \
              automake \
              cfitsio \
              fftw \
              hdf5 \
              pkg-config \
              swig
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - uses: actions/checkout@v2
        - name: "Software Install - Python"
          run: |
            pip install numpy
            pip install attrdict "importlib-metadata; python_version < '3.8'" "healpy < 1.14.0; python_version <= '2.7'"
            pip install -r requirements.txt
            pip install pylint
        - name: Build
          run: make
        - name: "Build and Install psrfits_utils"
          run: |
            git clone https://github.com/lwa-project/psrfits_utils.git
            cd psrfits_utils
            ./prepare
            ./configure
            make all
            cp ./.libs/*[sd][oy]* ./
            sudo make install
        - name: Test
          continue-on-error: ${{ matrix.python-version == '2.7' }}
          run: |
            cd tests
            python -m unittest discover
