name: Pulsar
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['2.7', '3.6', '3.8']
      fail-fast: false
    steps:
        - if: ${{ matrix.os == 'ubuntu-latest' }}
          run: |
            sudo apt-get install -y \
              build-essential \
              ca-certificates \
              curl \
              git \
              gzip \
              libcfitsio-dev \
              libfftw3-dev \
              libgdbm-dev \
              libhdf5-dev \
              pkg-config \
              tcsh \
              swig
        - if: ${{ matrix.os == 'macos-latest' }}
          run: |
            brew install \
              autoconf \
              automake \
              cfitsio \
              fftw \
              hdf5 \
              pkg-config \
              swig
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - uses: actions/checkout@v2
        - run: pip install setuptools numpy matplotlib scipy h5py 
        - run: pip install git+https://github.com/lwa-project/lsl.git
        - run: pip install pylint
        - run: make
        - run: git clone https://github.com/lwa-project/psrfits_utils.git
        - run: |
            cd psrfits_utils
            ./prepare
            ./configure
            make all
            cp ./.libs/*[sd][oy]* ./
            sudo make install
        - continue-on-error: ${{ matrix.python-version == '2.7' }}
          run: |
            cd tests
            python -m unittest discover
